server:
  port: 8080

spring:
  application:
    name: product-api

  datasource:
    #Update the following properties according to your PostgreSQL setup
    url: jdbc:postgresql://localhost:5432/productdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always          # Executes schema.sql and data.sql
      platform: postgres

  jpa:
    hibernate:
      ddl-auto: none        # IMPORTANT: schema controlled by SQL scripts
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.product: DEBUG
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
